[package]
name = "primes"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rayon = "1.7.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false

[[bin]]
name="primes"
